<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Moodle in English</name>
   <tag></tag>
   <elementGuidId>6ea63349-67b7-4289-811c-42aa3944dc33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_18_1_1_1701769210123_43']/div[3]/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.aalink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b859fa34-88f0-4b6c-b911-9d301dddd138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aalink</value>
      <webElementGuid>4ea55f23-4f75-457b-8d9b-6a72975005d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://moodle.org/course/view.php?id=5</value>
      <webElementGuid>f0ac9732-713a-4c6b-bc9b-0cc4c5dde30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moodle in English</value>
      <webElementGuid>2f5dc589-494c-42e1-b22e-fc8c2458090c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_18_1_1_1701769210123_43&quot;)/div[@class=&quot;course_category_tree clearfix&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;courses category-browse category-browse-3&quot;]/div[@class=&quot;coursebox clearfix odd first collapsed&quot;]/div[@class=&quot;info&quot;]/div[@class=&quot;coursename&quot;]/a[@class=&quot;aalink&quot;]</value>
      <webElementGuid>be94b778-9975-4563-ba41-5d73f8d56929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_18_1_1_1701769210123_43']/div[3]/div/div/div/div/div/a</value>
      <webElementGuid>c3e12193-a8bb-4f7b-a19e-07124f31d28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Moodle in English')]</value>
      <webElementGuid>56a69c28-79b6-4a89-a6f6-581763f683ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://moodle.org/course/view.php?id=5')]</value>
      <webElementGuid>282a22f8-8611-45b9-abf5-25a9e1d99bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>d75b7afa-afe1-45d4-85ed-3a35e34162a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://moodle.org/course/view.php?id=5' and (text() = 'Moodle in English' or . = 'Moodle in English')]</value>
      <webElementGuid>223eca5c-baac-4dfe-8049-e46461d4e6b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
