<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mi</name>
   <tag></tag>
   <elementGuidId>f4b1ca96-f677-408c-8720-f1a49846a4c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec6a442f-ecdd-4765-8662-b08b26678dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mi</value>
      <webElementGuid>d56eed97-34ca-42b7-a3eb-cb24be265767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3QN6WI</value>
      <webElementGuid>33c4c249-a89d-4953-bebf-0d935bfe314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mobiles/mi~brand/pr?sid=tyy,4io&amp;otracker=nmenu_sub_Electronics_0_Mi</value>
      <webElementGuid>3fe86572-b13b-4b01-92ed-1b8075905571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mi</value>
      <webElementGuid>3bc9aa87-76c3-4b6c-ba34-61c343a5c60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_331-kn&quot;]/div[@class=&quot;_3Il5oO dwRsDN&quot;]/div[@class=&quot;_1kidPb&quot;]/div[@class=&quot;_1QrT3s&quot;]/div[@class=&quot;_1fwVde&quot;]/a[@class=&quot;_3QN6WI&quot;]</value>
      <webElementGuid>c53dcee4-8bde-433e-9fa2-10355bfc7725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div/div/a[2]</value>
      <webElementGuid>7fee8a06-87a3-42c8-a877-f509f1b5a692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mi')]</value>
      <webElementGuid>cb4e0f17-eaac-4711-a2a6-c758491a56e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mobiles/mi~brand/pr?sid=tyy,4io&amp;otracker=nmenu_sub_Electronics_0_Mi')]</value>
      <webElementGuid>63d0885e-b73b-488b-a3df-036af670a941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a[2]</value>
      <webElementGuid>55665a27-f0d4-4dfc-8780-014cd7ee8a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Mi' and @href = '/mobiles/mi~brand/pr?sid=tyy,4io&amp;otracker=nmenu_sub_Electronics_0_Mi' and (text() = 'Mi' or . = 'Mi')]</value>
      <webElementGuid>7794b22d-8ad2-42f7-b6a7-5002fdbdddee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
