<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__2IX_2- VJZDxU</name>
   <tag></tag>
   <elementGuidId>1354114d-6f6f-424d-b8d9-f750feafd8b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input._2IX_2-.VJZDxU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>037fdf96-d600-4485-b803-8d6f41f81118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c40fce2f-3f36-4aad-b431-616cdf20615c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>50e2ab49-e9e7-4ef7-8d39-c0febdb431af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be445aa9-3a26-4062-9994-19b41ea051d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2IX_2- VJZDxU</value>
      <webElementGuid>dc37cb48-91fa-4c9c-b2bd-5254177c77d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_2dSUjN&quot;]/div[@class=&quot;_3wFoIb row gVNVNU&quot;]/div[@class=&quot;_36HLxm col col-3-5&quot;]/div[1]/form[1]/div[@class=&quot;IiD88i _351hSN&quot;]/input[@class=&quot;_2IX_2- VJZDxU&quot;]</value>
      <webElementGuid>11d5bb3c-1bd1-40f9-8d6b-aab490b020bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>e590d7e7-e69e-4c18-907a-5589f5e394ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div/form/div/input</value>
      <webElementGuid>04e05d4d-fd31-48be-8079-043e86980153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/form/div/input</value>
      <webElementGuid>78144664-1855-4a20-970c-213e7fa145b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>dc76aa9b-f069-4740-a208-bf749b198aa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
