<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>14988259-5746-4433-bea5-0f93ec909761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='js-nav']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.site-nav__button.right-nav__button.right-nav__button--login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad3e16df-9616-443f-8fe7-535b708905c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.podia.com/login</value>
      <webElementGuid>5bdf40f9-40a0-4a5a-b3e6-e4b94a6d6ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__button right-nav__button right-nav__button--login</value>
      <webElementGuid>802ec23b-fdc7-4993-94e5-8c05435412a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ef0abba6-81df-43b9-b4d0-cb2f8adb5f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-nav&quot;)/div[@class=&quot;banner__content container js-main-nav&quot;]/ul[@class=&quot;right-nav&quot;]/li[@class=&quot;guest-buttons&quot;]/a[@class=&quot;site-nav__button right-nav__button right-nav__button--login&quot;]</value>
      <webElementGuid>584f1e78-3bbc-4972-a19d-18ff7d580d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='js-nav']/div/ul/li/a</value>
      <webElementGuid>28dc0a6a-55f4-41b2-aeb6-00aeb52864c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>76abff04-f3bc-464e-96ba-5d980d8f9924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app.podia.com/login')]</value>
      <webElementGuid>ef1f4c3b-01df-4765-9108-46b15170cef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>f5a1dc19-8d63-4eb6-b8c6-7cdf4bc03c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app.podia.com/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>0ccdefa1-3717-4cd7-b787-9c4a4834d334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
