<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Page-header-menu-trigger</name>
   <tag></tag>
   <elementGuidId>63a1641f-4257-482d-946a-e295322abf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bsp-header[@id='rails-main-nav']/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Page-header-menu-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65c9d1eb-3056-4a50-8a5f-8189e7cb5e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Page-header-menu-trigger</value>
      <webElementGuid>6ac3cbb0-3ae0-4b19-9eb3-33d8b449c102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rails-main-nav&quot;)/div[@class=&quot;Page-header-bar&quot;]/button[@class=&quot;Page-header-menu-trigger&quot;]</value>
      <webElementGuid>aa30a0e8-0543-49b8-9cda-5764d037f248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//bsp-header[@id='rails-main-nav']/div[2]/button</value>
      <webElementGuid>3880cb26-3442-4b06-b35b-10a757382916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>6e5a932e-9689-46b6-aa33-6e6f12731107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
