<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_display-name</name>
   <tag></tag>
   <elementGuidId>f9c40bf9-b38e-4212-8ec6-15aca5b38d9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='display-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#display-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58c8f5e0-050a-4121-948a-96e4a1a4f9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex--item s-input</value>
      <webElementGuid>31aceba9-4698-4ff0-a88e-5ca8ebdf9043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d5109a2-2ae4-4b1b-b178-ea3e3d826db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>display-name</value>
      <webElementGuid>cc994872-9c08-4edb-bb9e-80bf8e05aeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display-name</value>
      <webElementGuid>d93f9155-4bae-406f-b8fc-1351567d1373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-teams</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75550c21-4494-4dff-a93f-4a51be8adcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display-name&quot;)</value>
      <webElementGuid>1f8eed7a-6254-48b1-9f7e-820905a76908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='display-name']</value>
      <webElementGuid>e1bfd8ec-8f8f-420b-9487-761db4d85a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div/input</value>
      <webElementGuid>2793e352-f9a2-4450-b302-90b6ea318579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>fc503ada-c856-4177-a1df-0851a1a8c1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'display-name' and @id = 'display-name']</value>
      <webElementGuid>fdc9a539-cee8-4921-96c2-e722521a9fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
