<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up</name>
   <tag></tag>
   <elementGuidId>e5054c97-a6aa-4268-b9e8-f87a0d68089b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Sign up')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.s-topbar--item.s-topbar--item__unset.ml4.s-btn.s-btn__filled.ws-nowrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7eee6189-f866-49cd-b9e1-fff21d437734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://stackoverflow.com/users/signup?ssrc=head&amp;returnurl=https%3a%2f%2fstackoverflow.com%2fquestions%2f68986231%2fwordpress-website-doesnt-appear-like-the-demo</value>
      <webElementGuid>c73aa0ed-2543-4280-ab3d-7d277c15038e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-topbar--item s-topbar--item__unset ml4 s-btn s-btn__filled ws-nowrap</value>
      <webElementGuid>e671914a-8948-4d86-9d11-0cde7db0d290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e00929da-634a-4eb5-b3fd-642bfa0682e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>deb2b0e8-aa6f-4e60-ad63-2c4b320e63cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga</name>
      <type>Main</type>
      <value>[&quot;sign up&quot;,&quot;Sign Up Navigation&quot;,&quot;Header&quot;,null,null]</value>
      <webElementGuid>06e909ec-5b95-4d28-a8bf-899d6e31ae0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>b4b27570-f23f-40da-9ec7-052745f599e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;html__responsive&quot;]/body[@class=&quot;question-page unified-theme&quot;]/header[@class=&quot;s-topbar ps-fixed t0 l0 js-top-bar&quot;]/div[@class=&quot;s-topbar--container&quot;]/nav[@class=&quot;h100 ml-auto overflow-x-auto pr12&quot;]/ol[@class=&quot;s-topbar--content&quot;]/li[4]/a[@class=&quot;s-topbar--item s-topbar--item__unset ml4 s-btn s-btn__filled ws-nowrap&quot;]</value>
      <webElementGuid>b3769363-e60c-4877-a299-85c4069d807b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign up')])[2]</value>
      <webElementGuid>8f2a093a-5859-456e-897a-72684627a9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://stackoverflow.com/users/signup?ssrc=head&amp;returnurl=https%3a%2f%2fstackoverflow.com%2fquestions%2f68986231%2fwordpress-website-doesnt-appear-like-the-demo')]</value>
      <webElementGuid>874a9a57-ed76-4717-94e9-bc5f6957a928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ol/li[4]/a</value>
      <webElementGuid>ee3add4e-6f63-490a-be17-9d204db9ac07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://stackoverflow.com/users/signup?ssrc=head&amp;returnurl=https%3a%2f%2fstackoverflow.com%2fquestions%2f68986231%2fwordpress-website-doesnt-appear-like-the-demo' and (text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>a1985785-aaf1-4f2a-86cd-0b4f33756184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
