<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_birth_day</name>
   <tag></tag>
   <elementGuidId>c7ab0a21-923c-4451-af52-9b23e3c6ffda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;birth_day&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='birth_day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f216f8c-12b3-44b5-8826-18cbc706c1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>day-input</value>
      <webElementGuid>71699111-074b-4d18-8775-0474845cb95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birth_day</value>
      <webElementGuid>affb4588-1e0d-4dd2-b9ab-552b7c18011b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>cff3e428-31cf-4999-93fd-4eecfea659fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>70a799ca-576c-4a0e-88d8-b8e0109799b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>999995d0-ad12-4dec-a787-e32f22237f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_form&quot;)/div[@class=&quot;field-container&quot;]/div[1]/div[2]/div[@class=&quot;sds-control sds-input&quot;]/div[@class=&quot;sds-input-base&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused&quot;]/input[@class=&quot;ant-input&quot;]</value>
      <webElementGuid>d1959bd1-3dc8-4238-b2db-f15f3753cb32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='birth_day']</value>
      <webElementGuid>ce2f2ac4-1d18-40f8-b230-7edfad9c4c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form']/div[6]/div/div[2]/div/div/span/input</value>
      <webElementGuid>644db612-382f-4499-8ec9-c2530fe68b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span/input</value>
      <webElementGuid>5f0bae3f-a06e-494b-b865-7ef442f80085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'birth_day' and @placeholder = 'Day' and @type = 'number']</value>
      <webElementGuid>ae8561ef-cf24-4dea-8a9d-5af61ce79be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
