<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>d4e24778-6799-4cab-8093-e6f3ba693c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tlp-header-user-nav']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.shared-global_header-user_nav_component__guestUserMenuLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd983a59-2244-4424-bcdf-bbc04eb77430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shared-global_header-user_nav_component__guestUserMenuLink</value>
      <webElementGuid>86f6698b-6ffd-4ffe-8935-45f5fc6b06fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sign_in</value>
      <webElementGuid>000f0912-f68a-4ef2-b6f4-3dd07b9fbf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-turbo</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23bce631-49cb-44cc-9a1c-a3e20bca64fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-controller</name>
      <type>Main</type>
      <value>modal-commander</value>
      <webElementGuid>16c3ff0b-8ccb-46f6-8dcd-b5125c913771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>modal-commander#open analytics-event#send</value>
      <webElementGuid>29351318-9974-4352-a3b9-071281b41327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal-commander-url-value</name>
      <type>Main</type>
      <value>/storefront/sign_in</value>
      <webElementGuid>10e648e8-c596-4e1b-8038-bbb46b9c7683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-event</name>
      <type>Main</type>
      <value>{&quot;hitType&quot;:&quot;event&quot;,&quot;eventCategory&quot;:&quot;page-header-top&quot;,&quot;eventAction&quot;:&quot;click;link&quot;,&quot;eventLabel&quot;:&quot;sign in&quot;}</value>
      <webElementGuid>2559ed89-9a85-471a-b46f-c3be31044388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Sign In
      </value>
      <webElementGuid>a31a8ba9-94dc-47b9-997b-61c79d596473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tlp-header-user-nav&quot;)/div[@class=&quot;shared-global_header-dropdown_component__guestUserMenuWrapper shared-global_header-dropdown_component__disabled&quot;]/a[@class=&quot;shared-global_header-user_nav_component__guestUserMenuLink&quot;]</value>
      <webElementGuid>48f37883-c46b-4e3a-b77e-121da7e5d27b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='tlp-header-user-nav']/div/a</value>
      <webElementGuid>1cf08a60-edb0-49a3-9622-9bfa90e8fc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/sign_in')]</value>
      <webElementGuid>ef247495-0f58-45d9-b9d5-e4dd17e531bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>45d9b68f-1fe4-4495-8f68-248d92b9ba18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/sign_in' and (text() = '
        Sign In
      ' or . = '
        Sign In
      ')]</value>
      <webElementGuid>022baa44-8a79-41bc-af3c-13f7a9604948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
