<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Password</name>
   <tag></tag>
   <elementGuidId>ede9e81d-9c57-4f1f-8958-dedf4b7e8dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forms-root']/div/div/form/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>509f3968-9a28-4eed-a7bf-31cc58dcae33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ikkxIA ghIuyE</value>
      <webElementGuid>ed7862d2-c7be-4e41-903e-4283c2d49035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>64ddd072-b9c9-47d2-bd2a-971ce45708f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8ea6c82d-ec97-45d2-9b8c-e235e602de66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forms-root&quot;)/div[@class=&quot;sc-kdBSHD ksjXvw&quot;]/div[@class=&quot;sc-imWYAI sc-tagGq dXWkvI krlRAc&quot;]/form[@class=&quot;sc-eldPxv hEtezd&quot;]/div[@class=&quot;sc-imWYAI sc-fPXMVe cIMMqX iZqZog&quot;]/div[@class=&quot;sc-aXZVg eggJqX sc-eqUAAy sc-hzhJZQ hpxZmX eAIYbP label-container&quot;]/label[@class=&quot;sc-ikkxIA ghIuyE&quot;]</value>
      <webElementGuid>5ac0943d-49df-4bb3-8dab-974a1af4f512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forms-root']/div/div/form/div[2]/div/label</value>
      <webElementGuid>824c55f8-b6d3-4337-a2c6-d1d98b56cae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/label</value>
      <webElementGuid>8cb0bf1d-f377-4329-84c5-7aa545767026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>070cd20c-8829-4393-b90e-60a3f334c460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
