<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Demos</name>
   <tag></tag>
   <elementGuidId>4daf6cb2-efeb-4de0-b062-59979d267789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-663']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-663 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ef8fa3f-ce68-4ee6-af76-8b411fa44795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://wpdemo.net/demos</value>
      <webElementGuid>fd79ee27-c787-460d-bc47-8a7cee1f39ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wpel-link</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>11f2c0b9-8885-4193-9ac0-11e51e18fa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demos</value>
      <webElementGuid>dafb1db7-f51d-43ce-9387-0d5d94a6b9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-663&quot;)/a[1]</value>
      <webElementGuid>b17297ff-ef4b-4b40-a184-81837856e2cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-663']/a</value>
      <webElementGuid>ae3a85ab-5a97-4e70-8059-c999d6e7bc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Demos')]</value>
      <webElementGuid>03ea5377-2323-432a-87db-1b5204e3fe4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://wpdemo.net/demos')]</value>
      <webElementGuid>ead09cfe-7e12-47fa-b368-41da25af2ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>17d846d8-6cc8-4f74-8348-d42f54904df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://wpdemo.net/demos' and (text() = 'Demos' or . = 'Demos')]</value>
      <webElementGuid>dcd0e92a-a643-4f71-8367-6e0c32193d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
