<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Service</name>
   <tag></tag>
   <elementGuidId>66742bc6-dd96-4efd-bc99-4c7155905d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-317']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-317 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3317160-eab5-451d-bb32-6aa5e7322b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://wpdemo.net/service</value>
      <webElementGuid>0391f2a9-e9b1-4382-a482-8da04c972566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wpel-link</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>bf644b3c-16af-460f-880a-a5668df08541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Service</value>
      <webElementGuid>01274122-47cf-4ad0-8e7e-d279a457609e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-317&quot;)/a[1]</value>
      <webElementGuid>29ccd71d-8784-4631-b55a-4cddd2a8230e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-317']/a</value>
      <webElementGuid>45d85abc-52a1-4915-bbb8-9ecb6f593c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Service')]</value>
      <webElementGuid>6e3c3afc-facd-4061-8564-0de3177cb15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://wpdemo.net/service')]</value>
      <webElementGuid>351db2b0-3a24-461c-bb6a-f45bc6f65e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>d0d8a5a6-c5e9-4211-bab6-63685b2ff396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://wpdemo.net/service' and (text() = 'Service' or . = 'Service')]</value>
      <webElementGuid>8917f625-e45e-44a7-96c8-e98632c5ff1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
