<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Managed WordPress hosting</name>
   <tag></tag>
   <elementGuidId>0bb3f9ce-a320-4134-bf18-495dac239cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='js-off-canvas']/nav/ul/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.off-canvas__nav.off-canvas-accordion > div > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f53257a-e0ab-494b-9799-9dbd73d8d2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://getflywheel.com/managed-wordpress-hosting/</value>
      <webElementGuid>f085a9a0-8d3d-41d5-8a85-b25cd433bb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Managed WordPress hosting</value>
      <webElementGuid>9c08c8b2-a6a1-4ca3-8d4f-717f53671b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-off-canvas&quot;)/nav[1]/ul[@class=&quot;off-canvas__nav off-canvas-accordion&quot;]/div[1]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>3ef271e1-6da0-4203-bf80-2d05e53bf77b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='js-off-canvas']/nav/ul/div/ul/li/a</value>
      <webElementGuid>f73bb5e1-f7b1-43d2-85a5-dbb56b9ccb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Managed WordPress hosting')])[2]</value>
      <webElementGuid>bca0e75d-0f98-4cf1-90a1-06c148f3c779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://getflywheel.com/managed-wordpress-hosting/')])[2]</value>
      <webElementGuid>ef846c5a-41ec-433e-a1c5-2e8aa5d55ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/ul/li/a</value>
      <webElementGuid>9d2e060d-ac8f-4ac4-8d50-6339c62908fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://getflywheel.com/managed-wordpress-hosting/' and (text() = 'Managed WordPress hosting' or . = 'Managed WordPress hosting')]</value>
      <webElementGuid>4395cde6-a194-49f9-81ae-7174bc7d2412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
