<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_header__hamburger__line</name>
   <tag></tag>
   <elementGuidId>78446c18-261f-438b-a201-7ae847c673f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-offcanvas-trigger']/div/div[2]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6cd90e03-0ae7-44de-97e8-76faca4861e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__hamburger__line</value>
      <webElementGuid>06cfda22-86bc-4c9d-b560-679faaf9bb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-offcanvas-trigger&quot;)/div[@class=&quot;hamburger__container&quot;]/div[@class=&quot;hamburger__lines&quot;]/span[@class=&quot;header__hamburger__line&quot;]</value>
      <webElementGuid>9c33f75d-0193-4d4d-a2ab-402134bb148a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='js-offcanvas-trigger']/div/div[2]/span[3]</value>
      <webElementGuid>e75d993a-9b28-4c2a-8557-086f6a1fcef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>a85c7cfc-b100-4bde-933b-2b52c5f2fb3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
