<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Membership</name>
   <tag></tag>
   <elementGuidId>6f1db7ef-8946-46a1-8593-66c482b9ff60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='menu-main-2']/li[3]/a/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-22691.depth-0.sfHover > a.link.link-depth-0 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22902221-2a80-4966-8607-ab867941e09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Membership</value>
      <webElementGuid>08499676-d4bb-4931-8e53-8c7791ddcc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/header[@id=&quot;site-header&quot;]/div[@class=&quot;inside logo-and-nav clearfix&quot;]/div[@class=&quot;nav-holder&quot;]/div[@class=&quot;main-nav clearfix&quot;]/ul[@id=&quot;menu-main-2&quot;]/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-22691 depth-0 sfHover&quot;]/a[@class=&quot;link link-depth-0&quot;]/span[1]</value>
      <webElementGuid>a8e82769-83f3-4280-a57c-8d0655e31bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='menu-main-2']/li[3]/a/span)[2]</value>
      <webElementGuid>909f03d8-c88d-4fcb-a432-41d2ea2eea74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/header/div[2]/div[2]/div/ul/li[3]/a/span</value>
      <webElementGuid>adf74d0d-46cd-4f05-9cfd-5d60796aa744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Membership' or . = 'Membership')]</value>
      <webElementGuid>24064618-2788-403a-a865-58a22d4605b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
