<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Plugins</name>
   <tag></tag>
   <elementGuidId>c7559ae7-5b60-4919-bf24-6c92324cef2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-122657']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-122657 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6acae1e3-84f0-4755-aa9c-07db0ac50727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://themify.me/plugins</value>
      <webElementGuid>bcef847e-2797-4cb8-980f-695b9162e48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plugins</value>
      <webElementGuid>32d157ea-5f2a-496a-8512-a994127dad1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-122657&quot;)/a[1]</value>
      <webElementGuid>b91cce1b-0c61-4c6e-8772-a382dd2a1f33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-122657']/a</value>
      <webElementGuid>d1af6627-b449-428c-94db-82eae24a93bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Plugins')]</value>
      <webElementGuid>aebf54d7-3f9c-4b92-932c-721d33505fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://themify.me/plugins')]</value>
      <webElementGuid>65643c1e-d545-4291-a771-1d60075b139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>bd7c1019-7906-46c4-8c5d-a72202977387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://themify.me/plugins' and (text() = 'Plugins' or . = 'Plugins')]</value>
      <webElementGuid>6a806537-7937-4490-bc66-4a7c9b558c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
