<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edd_user_login</name>
   <tag></tag>
   <elementGuidId>6c581816-8d6d-4f43-aa0f-373c34e7b38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edd_user_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edd_user_login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48bbf78b-aadc-4478-8a98-c4a70015efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>edd_user_login</value>
      <webElementGuid>6eb1d14c-f0d5-4627-b850-bca850fcd9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edd_user_login</value>
      <webElementGuid>f5173320-10fb-4572-ad3e-d8b961d2773a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edd-required edd-input</value>
      <webElementGuid>35934ac7-276c-4c20-8320-189f70f605c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2503b726-3bb5-4f7e-8dd9-9b16a1383725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edd_user_login&quot;)</value>
      <webElementGuid>c190275b-4c22-4b4a-89ba-837c3f01bf70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edd_user_login']</value>
      <webElementGuid>ecd6a7dc-fcc9-4523-8860-0cbebd7f99e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edd_login_form']/fieldset/p/input</value>
      <webElementGuid>bd2b1545-7133-4ce0-ba55-97e9cedaa8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8ea8cb1e-0071-4cea-a2af-639bfee4dc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'edd_user_login' and @id = 'edd_user_login' and @type = 'text']</value>
      <webElementGuid>ce95c56a-38ee-4d2b-aa29-655690ff0232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
