<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sitepad-search-field</name>
   <tag></tag>
   <elementGuidId>0c31a50f-3504-490b-b7a5-f8a0bebd6789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popularfx_search']/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sitepad-search-field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>829e516f-04c3-489e-9712-a69579ef46d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sitepad-search-field</value>
      <webElementGuid>cd7d5a3e-2dae-4733-aedb-8e1bba76b8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popularfx_search&quot;)/div[@class=&quot;sitepad-search&quot;]/input[@class=&quot;sitepad-search-field&quot;]</value>
      <webElementGuid>16a6ca15-f5ee-497e-a0f8-d828b7d20960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popularfx_search']/div[2]/input</value>
      <webElementGuid>8813d3e9-f241-4246-b56f-0a6224e1473b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>66d7a774-5210-457e-ba22-8c8965b5bff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
