<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__18u87m _3WuvDp</name>
   <tag></tag>
   <elementGuidId>4be30375-17cc-4d45-9489-5c1f6b94b75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input._18u87m._3WuvDp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50e32f2c-1d8c-4ea4-a5c4-0cfebb834255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dae5cc51-8cff-4971-aaed-d847b05f7843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ee25357-8aff-4851-b964-7214ccc5a151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_18u87m _3WuvDp</value>
      <webElementGuid>4482ba29-2506-41a2-a8d7-e6eb3dbc5abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d22e898-9cf0-4ee2-98cc-2ce9bea7f762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[@class=&quot;fk-modal-visible&quot;]/div[@class=&quot;fbDBuK _3CYmv5&quot;]/div[@class=&quot;JFPqaw&quot;]/div[@class=&quot;_17UxrZ&quot;]/div[@class=&quot;_1E5Hij&quot;]/div[@class=&quot;_3skCyB&quot;]/div[1]/form[1]/div[@class=&quot;_22Dgdy _29BEA8&quot;]/input[@class=&quot;_18u87m _3WuvDp&quot;]</value>
      <webElementGuid>e0b10fcc-9ca9-4467-a3a5-f07ab39ff996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>3c0bc6d5-1aae-473c-b206-1558196f93eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/input</value>
      <webElementGuid>72aed6c7-b686-457e-8bf0-1d8e5c827f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>317d89f5-621b-47d8-8654-1fdb30732941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
