<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__24_Dny</name>
   <tag></tag>
   <elementGuidId>1b919db8-bf44-44c2-a8e8-37002de642eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._24_Dny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/div[2]/div/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d602af42-7079-4b90-9ee5-4cb00da5c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_24_Dny</value>
      <webElementGuid>cce2ef9e-6483-4271-bdbf-14f8f829e4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-2-12&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-12-12&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_1KOcBL&quot;]/section[@class=&quot;_167Mu3 _2hbLCH&quot;]/div[@class=&quot;_3FPh42&quot;]/div[@class=&quot;_2d0we9&quot;]/div[@class=&quot;_4921Z t0pPfW&quot;]/div[@class=&quot;_1Y4Vhm _4FO7b6&quot;]/label[@class=&quot;_2iDkf8 t0pPfW&quot;]/div[@class=&quot;_24_Dny&quot;]</value>
      <webElementGuid>e7ac9097-27f3-4d23-8f75-a22f3eaf21aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/div[2]/div/div/div/label/div</value>
      <webElementGuid>144f64e7-6388-4d98-ba9d-448b0f13ab5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>a9967471-d9cd-47eb-b557-ce38ff454aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
