<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>48381519-566d-4467-a6b7-d4d46a41f1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ssoLoginButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ssoLoginButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebd97d91-b623-4001-8344-9f1da872a956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssoLoginButton</value>
      <webElementGuid>75136fb9-99d8-4964-a5da-fd816e053c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ssoLoginButton btn white dropshadow sm</value>
      <webElementGuid>0f8c7334-d9e9-48ca-ba94-5ddea6c90ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ssologin/?context=web&amp;uri=https%3A%2F%2Fdequeuniversity.com%2Fdemo%2F</value>
      <webElementGuid>89f14083-77df-424a-85ed-8eb36af4a661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a3fc9faa-3937-4eb6-bbab-f9df4b7c41fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssoLoginButton&quot;)</value>
      <webElementGuid>524519b3-47b2-45bc-835b-53290d836eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ssoLoginButton']</value>
      <webElementGuid>bc627132-5acb-4b93-bedf-8ca3b289aa5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inCourseLogin']/div/div/a</value>
      <webElementGuid>43f0e25d-2325-43d0-9809-8892bde4d6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>298b7204-8207-4587-b453-bde96b25b293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ssologin/?context=web&amp;uri=https%3A%2F%2Fdequeuniversity.com%2Fdemo%2F')]</value>
      <webElementGuid>cfc32350-9586-4204-a655-effa2b896569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>e9b3c07d-5ab0-4178-8bad-61446f68dfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ssoLoginButton' and @href = 'ssologin/?context=web&amp;uri=https%3A%2F%2Fdequeuniversity.com%2Fdemo%2F' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>6e8caff8-2d3e-41b0-b4cf-4dca3d506a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
