<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>ac556f64-e6a3-4b2d-8a16-3eb77c68f737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/section[2]/main/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9553cdea-cb93-4713-8927-3b2d0f238a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/session/new</value>
      <webElementGuid>b28c4c71-72d4-4e4b-9d5f-78ee4c368186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>7070d0d8-297d-42d6-bdde-e469b3e62ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/section[@class=&quot;content&quot;]/main[1]/div[@class=&quot;auth-content&quot;]/p[@class=&quot;auth-link color-deep-blue-sea-light-20&quot;]/a[1]</value>
      <webElementGuid>5652515b-03c7-4387-a835-9fe364c0faa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/section[2]/main/div/p[2]/a</value>
      <webElementGuid>1a8cfd4b-6b79-48cc-bdeb-d6c869dab80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign In')])[2]</value>
      <webElementGuid>ce497e74-ad6d-4562-9067-e9c323128b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/session/new')])[2]</value>
      <webElementGuid>4081a904-92ae-4ed9-acdf-b54cb1e40133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>29ad2288-b6c7-471e-97a4-6924aa759ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/session/new' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>b8201cbd-738c-4bed-a4f9-d2755cfd734c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
