<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Features</name>
   <tag></tag>
   <elementGuidId>603c6375-3281-4a1c-a5e1-0b4aec6c5bbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='menu-main-2']/li[2]/a/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-21284.depth-0.sfHover > a.link.link-depth-0 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9da9d218-7a13-4cb6-93a5-f753617afb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Features</value>
      <webElementGuid>81c6a928-7165-499f-8d9a-a894e03af4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/header[@id=&quot;site-header&quot;]/div[@class=&quot;inside logo-and-nav clearfix&quot;]/div[@class=&quot;nav-holder&quot;]/div[@class=&quot;main-nav clearfix&quot;]/ul[@id=&quot;menu-main-2&quot;]/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-21284 depth-0 sfHover&quot;]/a[@class=&quot;link link-depth-0&quot;]/span[1]</value>
      <webElementGuid>f882da52-1b6f-42c7-9a0e-7bc29e6a0ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='menu-main-2']/li[2]/a/span)[2]</value>
      <webElementGuid>5974e1a4-f679-47e0-9878-4ea0aaf2b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/header/div[2]/div[2]/div/ul/li[2]/a/span</value>
      <webElementGuid>6068402d-66aa-4abe-8371-104846993b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Features' or . = 'Features')]</value>
      <webElementGuid>0a9770d3-e7a9-4c21-a648-7e218efbf491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
