<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_( (Afaan OromooAfrikaansAfsoomaaliAr_74c430</name>
   <tag></tag>
   <elementGuidId>363f4589-41ff-4f52-8734-38471c9f01c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='language-switcher-locales']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#language-switcher-locales</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>078ba3bb-3d73-4c14-be4d-2d314a13c4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language-switcher-locales</value>
      <webElementGuid>a4ad9d8e-68b1-42e7-a9a5-b7ccb2464972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locale</value>
      <webElementGuid>2441c88c-436d-4b66-9aac-38427f409153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				(فارسی (افغانستانAfaan OromooAfrikaansAfsoomaaliAragonésArpitanAsturianuAsụsụ IgboAzərbaycan TürkcəsiAzərbaycan diliBahasa IndonesiaBahasa MelayuBasa JawaBasa SundaBosanskiBrezhonegCatalàCatalà (Balear)Català (Valencià)CebuanoChiShonaCh’tiCorsuCrnogorski jezikCymraegDanskDeutschDeutsch (Schweiz)Deutsch (Schweiz, Du)Deutsch (Sie)Deutsch (Österreich)DolnoserbšćinaEestiEnglishEnglish (Australia)English (Canada)English (New Zealand)English (Pirate)English (South Africa)English (UK)EspañolEspañol de ArgentinaEspañol de ChileEspañol de ColombiaEspañol de Costa RicaEspañol de EcuadorEspañol de GuatemalaEspañol de HondurasEspañol de MéxicoEspañol de PerúEspañol de Puerto RicoEspañol de República DominicanaEspañol de UruguayEspañol de VenezuelaEsperantoEuskaraEʋegbeFrançaisFrançais de BelgiqueFrançais du CanadaFriulianFryskFøroysktGaeligeGalegoGàidhligHarshen HausaHornjoserbšćinaHrvatskiIdoIkinyarwandaItalianoKalaallisutKernewekKiswahiliKreol MorisienKreyol ayisyenKurdîLatviešu valodaLietuvių kalbaLimburgsLombardoLëtzebuergeschLìgureMagyarMalagasyMaltiNederlandsNederlands (België)Nederlands (Formeel)NgalaNigerian PidginNorsk bokmålNorsk nynorskOccitanOlugandaO‘zbekchaPapiamentoPapiamentuPolskiPortuguêsPortuguês (AO90)Português de AngolaPortuguês do BrasilPulaarPër Kosovën ShqipQaraqalpaq tiliReo TahitiRomânăRumantschRuáingaSarduShqipSiSwatiSicilianuSlovenčinaSlovenščinaSuomiSvenskaSyriacTagalogTaqbaylitTe Reo MāoriTiếng ViệtTwentsTürkmençeTürkçeVènetoWolofYorùbáfɔ̀ngbèisiXhosaisiZuluÍslenskaČeštinaŚlōnskŏ gŏdkaΕλληνικάБеларуская моваБългарскиИронКыргызчаМакедонски јазикМонголРусскийСахалыыСрпски језикТатар телеТоҷикӣУкраїнськаҚазақ тіліՀայերենעִבְרִיתئۇيغۇرچەاردوالدارجة الجزايريةالعربيةالعربية المغربيةبلوچی مکرانیسرائیکیسنڌيفارسیكوردی‎هزاره گیپښتوگؤنئی آذربایجانދިވެހިߒߞߏनेपालीबोडो‎भारतम्भोजपुरीमराठीमैथिलीहिन्दीঅসমীয়াবাংলাবাংলা (ভারত)ਪੰਜਾਬੀગુજરાતીଓଡ଼ିଆதமிழ்தமிழ்తెలుగుಕನ್ನಡമലയാളംසිංහලไทยພາສາລາວབོད་ཡིགརྫོང་ཁဗမာစာქართულიትግርኛአማርኛភាសាខ្មែរⵜⴰⵎⴰⵣⵉⵖⵜⵜⴰⵎⴰⵣⵉⵖⵜ中文日本語简体中文繁體中文香港中文한국어🌏🌍🌎 (Emoji)			</value>
      <webElementGuid>8fe55b7b-8610-4e2b-a9e3-9c3f9e310b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;language-switcher-locales&quot;)</value>
      <webElementGuid>34b0e68d-1216-40f2-b077-9cfdb9be3450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='language-switcher-locales']</value>
      <webElementGuid>8ec36783-3862-49cd-ad9d-ab2ce025c579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='language-switcher']/select</value>
      <webElementGuid>8a5ffccd-1aa5-4bb6-8548-1940bc656e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>87afb09e-146d-4a12-be6f-7d478e2f66f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'language-switcher-locales' and @name = 'locale' and (text() = '
				(فارسی (افغانستانAfaan OromooAfrikaansAfsoomaaliAragonésArpitanAsturianuAsụsụ IgboAzərbaycan TürkcəsiAzərbaycan diliBahasa IndonesiaBahasa MelayuBasa JawaBasa SundaBosanskiBrezhonegCatalàCatalà (Balear)Català (Valencià)CebuanoChiShonaCh’tiCorsuCrnogorski jezikCymraegDanskDeutschDeutsch (Schweiz)Deutsch (Schweiz, Du)Deutsch (Sie)Deutsch (Österreich)DolnoserbšćinaEestiEnglishEnglish (Australia)English (Canada)English (New Zealand)English (Pirate)English (South Africa)English (UK)EspañolEspañol de ArgentinaEspañol de ChileEspañol de ColombiaEspañol de Costa RicaEspañol de EcuadorEspañol de GuatemalaEspañol de HondurasEspañol de MéxicoEspañol de PerúEspañol de Puerto RicoEspañol de República DominicanaEspañol de UruguayEspañol de VenezuelaEsperantoEuskaraEʋegbeFrançaisFrançais de BelgiqueFrançais du CanadaFriulianFryskFøroysktGaeligeGalegoGàidhligHarshen HausaHornjoserbšćinaHrvatskiIdoIkinyarwandaItalianoKalaallisutKernewekKiswahiliKreol MorisienKreyol ayisyenKurdîLatviešu valodaLietuvių kalbaLimburgsLombardoLëtzebuergeschLìgureMagyarMalagasyMaltiNederlandsNederlands (België)Nederlands (Formeel)NgalaNigerian PidginNorsk bokmålNorsk nynorskOccitanOlugandaO‘zbekchaPapiamentoPapiamentuPolskiPortuguêsPortuguês (AO90)Português de AngolaPortuguês do BrasilPulaarPër Kosovën ShqipQaraqalpaq tiliReo TahitiRomânăRumantschRuáingaSarduShqipSiSwatiSicilianuSlovenčinaSlovenščinaSuomiSvenskaSyriacTagalogTaqbaylitTe Reo MāoriTiếng ViệtTwentsTürkmençeTürkçeVènetoWolofYorùbáfɔ̀ngbèisiXhosaisiZuluÍslenskaČeštinaŚlōnskŏ gŏdkaΕλληνικάБеларуская моваБългарскиИронКыргызчаМакедонски јазикМонголРусскийСахалыыСрпски језикТатар телеТоҷикӣУкраїнськаҚазақ тіліՀայերենעִבְרִיתئۇيغۇرچەاردوالدارجة الجزايريةالعربيةالعربية المغربيةبلوچی مکرانیسرائیکیسنڌيفارسیكوردی‎هزاره گیپښتوگؤنئی آذربایجانދިވެހިߒߞߏनेपालीबोडो‎भारतम्भोजपुरीमराठीमैथिलीहिन्दीঅসমীয়াবাংলাবাংলা (ভারত)ਪੰਜਾਬੀગુજરાતીଓଡ଼ିଆதமிழ்தமிழ்తెలుగుಕನ್ನಡമലയാളംසිංහලไทยພາສາລາວབོད་ཡིགརྫོང་ཁဗမာစာქართულიትግርኛአማርኛភាសាខ្មែរⵜⴰⵎⴰⵣⵉⵖⵜⵜⴰⵎⴰⵣⵉⵖⵜ中文日本語简体中文繁體中文香港中文한국어🌏🌍🌎 (Emoji)			' or . = '
				(فارسی (افغانستانAfaan OromooAfrikaansAfsoomaaliAragonésArpitanAsturianuAsụsụ IgboAzərbaycan TürkcəsiAzərbaycan diliBahasa IndonesiaBahasa MelayuBasa JawaBasa SundaBosanskiBrezhonegCatalàCatalà (Balear)Català (Valencià)CebuanoChiShonaCh’tiCorsuCrnogorski jezikCymraegDanskDeutschDeutsch (Schweiz)Deutsch (Schweiz, Du)Deutsch (Sie)Deutsch (Österreich)DolnoserbšćinaEestiEnglishEnglish (Australia)English (Canada)English (New Zealand)English (Pirate)English (South Africa)English (UK)EspañolEspañol de ArgentinaEspañol de ChileEspañol de ColombiaEspañol de Costa RicaEspañol de EcuadorEspañol de GuatemalaEspañol de HondurasEspañol de MéxicoEspañol de PerúEspañol de Puerto RicoEspañol de República DominicanaEspañol de UruguayEspañol de VenezuelaEsperantoEuskaraEʋegbeFrançaisFrançais de BelgiqueFrançais du CanadaFriulianFryskFøroysktGaeligeGalegoGàidhligHarshen HausaHornjoserbšćinaHrvatskiIdoIkinyarwandaItalianoKalaallisutKernewekKiswahiliKreol MorisienKreyol ayisyenKurdîLatviešu valodaLietuvių kalbaLimburgsLombardoLëtzebuergeschLìgureMagyarMalagasyMaltiNederlandsNederlands (België)Nederlands (Formeel)NgalaNigerian PidginNorsk bokmålNorsk nynorskOccitanOlugandaO‘zbekchaPapiamentoPapiamentuPolskiPortuguêsPortuguês (AO90)Português de AngolaPortuguês do BrasilPulaarPër Kosovën ShqipQaraqalpaq tiliReo TahitiRomânăRumantschRuáingaSarduShqipSiSwatiSicilianuSlovenčinaSlovenščinaSuomiSvenskaSyriacTagalogTaqbaylitTe Reo MāoriTiếng ViệtTwentsTürkmençeTürkçeVènetoWolofYorùbáfɔ̀ngbèisiXhosaisiZuluÍslenskaČeštinaŚlōnskŏ gŏdkaΕλληνικάБеларуская моваБългарскиИронКыргызчаМакедонски јазикМонголРусскийСахалыыСрпски језикТатар телеТоҷикӣУкраїнськаҚазақ тіліՀայերենעִבְרִיתئۇيغۇرچەاردوالدارجة الجزايريةالعربيةالعربية المغربيةبلوچی مکرانیسرائیکیسنڌيفارسیكوردی‎هزاره گیپښتوگؤنئی آذربایجانދިވެހިߒߞߏनेपालीबोडो‎भारतम्भोजपुरीमराठीमैथिलीहिन्दीঅসমীয়াবাংলাবাংলা (ভারত)ਪੰਜਾਬੀગુજરાતીଓଡ଼ିଆதமிழ்தமிழ்తెలుగుಕನ್ನಡമലയാളംසිංහලไทยພາສາລາວབོད་ཡིགརྫོང་ཁဗမာစာქართულიትግርኛአማርኛភាសាខ្មែរⵜⴰⵎⴰⵣⵉⵖⵜⵜⴰⵎⴰⵣⵉⵖⵜ中文日本語简体中文繁體中文香港中文한국어🌏🌍🌎 (Emoji)			')]</value>
      <webElementGuid>d2f9e25d-10ed-448a-b3dd-7020c29581d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
