<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>685ae481-239a-49e0-b4da-841b7eda4cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wp-admin-bar-register']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wp-admin-bar-register > a.ab-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc8107e6-dad2-4c70-9e7b-d361d9d08bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ab-item</value>
      <webElementGuid>30a31151-a78d-4542-ae47-b6870eba0ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://login.wordpress.org/register?locale=en_US</value>
      <webElementGuid>581f9d8e-822d-487b-90de-639de2c69afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>643b6d64-e639-475b-9e27-373e1d78d296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-admin-bar-register&quot;)/a[@class=&quot;ab-item&quot;]</value>
      <webElementGuid>c6806086-d5d3-4236-ab0f-653d71c38c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wp-admin-bar-register']/a</value>
      <webElementGuid>0249319a-f2ff-4027-a1bb-0cc80c048e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>fe290caa-0f3a-4f1b-b2a4-aa7fd77c0f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://login.wordpress.org/register?locale=en_US')]</value>
      <webElementGuid>2fd90df8-2b26-4b21-b6f6-4d1bc8fb3f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>613deb91-e78a-4fd7-82aa-25dd0e092161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://login.wordpress.org/register?locale=en_US' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>86e702d5-41b2-4894-8af3-21f6932de80a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
