<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Denim</name>
   <tag></tag>
   <elementGuidId>e5533674-e6be-4663-bfc5-4913ebb8977b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-344']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-344 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fae2249c-cce4-4bd2-b2fe-14bd3d8aca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/product-category/denim/</value>
      <webElementGuid>6df4d887-5873-4edc-87a5-ea49a355cc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Denim</value>
      <webElementGuid>e16f634f-a5f5-41e5-ac01-e754c0e6a963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-344&quot;)/a[1]</value>
      <webElementGuid>10397bcf-2e33-4cb8-b3a9-3a30c164b784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframeiframe</value>
      <webElementGuid>bb3ae7c3-c31a-4f65-a6d5-02aca3713170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-344']/a</value>
      <webElementGuid>1caa8b1c-b9f9-4d20-a763-a352f8704d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Denim')]</value>
      <webElementGuid>64dddd74-72f3-4ad0-b366-0b95a9cd1832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://modern-store.competethemes.com/product-category/denim/')]</value>
      <webElementGuid>91cd1dfc-5863-47f1-b62c-f46faae38e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/ul/li[4]/a</value>
      <webElementGuid>f6b14c02-f3dc-4ac3-8624-6e661b82c30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://modern-store.competethemes.com/product-category/denim/' and (text() = 'Denim' or . = 'Denim')]</value>
      <webElementGuid>7cf824e4-3cec-4658-b4a0-aa8133ec08b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
