<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Arrivals</name>
   <tag></tag>
   <elementGuidId>606d596b-1e16-489d-b2e3-d7feabd70842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-353']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-353 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a28027e-cb0b-4426-a48c-0ddcdb146f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/shop/</value>
      <webElementGuid>ba98091c-20e1-423b-a1ff-83806453ea78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Arrivals</value>
      <webElementGuid>b5351888-10d9-4c7b-b7e1-cd6ba9477aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-353&quot;)/a[1]</value>
      <webElementGuid>70467aa2-54b1-44eb-868f-fc5a9da6c999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframeiframe</value>
      <webElementGuid>dd55f251-ad10-4f33-9ec6-53b00398879c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-353']/a</value>
      <webElementGuid>e565d074-140e-4576-9717-51b40a4b6777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Arrivals')]</value>
      <webElementGuid>510ef974-e905-4fd4-899a-300f33984ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://modern-store.competethemes.com/shop/')]</value>
      <webElementGuid>b19f9a23-edee-4ae4-8360-1c954f373136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>30d33df5-699f-4d9f-9244-80029e9673cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://modern-store.competethemes.com/shop/' and (text() = 'New Arrivals' or . = 'New Arrivals')]</value>
      <webElementGuid>cf5438cf-25c6-4a93-a6f9-86b2467d7e0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
