<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new_phonenumber</name>
   <tag></tag>
   <elementGuidId>8949dd35-0122-4bdc-8dea-45a8e3ed9027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new_phonenumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new_phonenumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fecdc46a-1d1a-4ad4-837e-defecee6def7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_phonenumber</value>
      <webElementGuid>5279e4b1-809c-4d93-8299-616db3678664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef340131-3552-44da-9e71-a61ab6c9f876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc63825c-12c3-4784-a92e-8729c1a79af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new_phonenumber</value>
      <webElementGuid>0f2dbdf9-fa01-426a-b865-0d0bca4e58a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>9ff5f9e5-16d3-4cf0-a99d-fc138cae7685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f90d7b7c-48ec-461f-9dd3-f4beec275c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_phonenumber&quot;)</value>
      <webElementGuid>17950b06-77cf-4572-b563-8ac3c7e7b801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new_phonenumber']</value>
      <webElementGuid>e84da621-7061-4290-99e5-348d03280bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dw-form-5']/div/div[6]/div/input</value>
      <webElementGuid>35b9d968-ab39-4ccc-b462-58e50a43fc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>c7f2c684-5610-426d-8f08-5afeaface6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'new_phonenumber' and @type = 'text' and @name = 'new_phonenumber' and @placeholder = 'Phone']</value>
      <webElementGuid>4a600bb8-b767-4d57-a409-3688d2cf1e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
