<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Themes</name>
   <tag></tag>
   <elementGuidId>56e0e80b-20ed-48c3-a4a8-475a835646b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3617']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3617 > a > span.pagelayer-nav-menu-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa9f83b8-17bf-4576-b016-306e1dfff978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagelayer-nav-menu-title</value>
      <webElementGuid>9f7b8220-cbbe-42cb-acd6-384534237e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Themes</value>
      <webElementGuid>740b5d23-d6ef-4907-8882-881608f1e007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3617&quot;)/a[1]/span[@class=&quot;pagelayer-nav-menu-title&quot;]</value>
      <webElementGuid>2956f569-4eaa-4d30-8c18-bf896bd44231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3617']/a/span</value>
      <webElementGuid>c7b68c67-35ab-48f5-a008-f0af3357fbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>1e0432c1-e66c-4fd1-8050-92cab364e932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Themes' or . = 'Themes')]</value>
      <webElementGuid>da08bf6a-5676-41f0-81d8-ef7a92f3adcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
