<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Email address</name>
   <tag></tag>
   <elementGuidId>bbb05fb0-76a8-4352-a5aa-6848fcf47446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='react-spectrum-11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-spectrum-11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>94a05f1d-69bd-4d2a-8846-19b195f8f4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-FieldLabel</value>
      <webElementGuid>01fe1d5b-3c94-4bc1-9974-bcf49c116ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-spectrum-11</value>
      <webElementGuid>a53a688b-fba2-4eac-8c82-0933f247a4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>EmailPage-EmailField</value>
      <webElementGuid>cc9352af-bacd-4b46-90e8-e84b1470fb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>73e6adb4-a83e-434c-b246-971ee97cf9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-spectrum-11&quot;)</value>
      <webElementGuid>b83292ec-1ce8-4c8e-badd-0f70985a6a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='react-spectrum-11']</value>
      <webElementGuid>e31379ba-671e-49ff-82cc-a482c13da83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EmailForm']/section/div/label</value>
      <webElementGuid>38255840-2f9f-45a0-8ed4-2b64ed2b295c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>0f0a213a-1e90-40d2-971e-25ae9f7ffa90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'react-spectrum-11' and (text() = 'Email address' or . = 'Email address')]</value>
      <webElementGuid>d5b9c219-6690-44b5-a3b5-d0dd40ce13d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
