<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_preText2</name>
   <tag></tag>
   <elementGuidId>042aec88-9a2b-4ec1-8898-0ed71a76a068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myTextInput2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myTextInput2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>031da4e5-8c62-4a0e-9c07-9eae42153bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa7a01c2-63b4-456c-abad-c5333018f79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Text...</value>
      <webElementGuid>3438d407-4ca5-4323-952f-07c28ad03c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myTextInput2</value>
      <webElementGuid>076d2945-343c-47cd-af2e-46970881be7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preText2</value>
      <webElementGuid>5e44040f-562a-44c2-943d-9a7c0846a65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTextInput2&quot;)</value>
      <webElementGuid>ed599df4-0892-474a-b0be-c3f6a93586fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myTextInput2']</value>
      <webElementGuid>e1c6e376-60fe-4c1f-aa0c-e1e7061699f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbodyId']/tr[3]/td[2]/input</value>
      <webElementGuid>3a6e7195-7c55-46b5-abce-c7351a9f3edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>28d81747-d255-4d38-b7ca-f1641c75cb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'myTextInput2' and @name = 'preText2']</value>
      <webElementGuid>3b9891c9-5825-41d2-b64f-e96d072970b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
