<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputplaceholderText</name>
   <tag></tag>
   <elementGuidId>d841609a-37c4-4667-ba51-7f5ef5ecdba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='placeholderText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#placeholderText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aa239ac-b293-4057-9cba-dd8275a9d494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placeholderText</value>
      <webElementGuid>1e3e55b7-c400-4d04-96d8-62d62d27e811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a80c5fe7-a7f8-4826-a1f2-6ce186f327df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Placeholder Text Field</value>
      <webElementGuid>fcc13495-93e1-4334-9c9d-2a66140c3d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeholderText&quot;)</value>
      <webElementGuid>89a36418-1f51-4c09-ab7e-532008702a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='placeholderText']</value>
      <webElementGuid>9b5d7a75-99ef-4f9a-b3fe-90b6549f242c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbodyId']/tr[4]/td[2]/input</value>
      <webElementGuid>8d403713-dd69-4822-b5f2-f7cef6edbf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>097f4158-f1ad-4fcf-90e0-9b879fbd572d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'placeholderText' and @type = 'text' and @placeholder = 'Placeholder Text Field']</value>
      <webElementGuid>80ab95d3-063a-4183-a5f4-63c59d61373c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
